source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.2.0"
gem "pg", "~> 1.5"
gem "neighbor", "~> 0.5"
gem "ruby-openai", "~> 7.0"
gem "puma", "~> 6.0"

group :development do
  gem "debug"
end
